// vue-aplikacja/src/components/TestUAM.vue
<template>
  <div id="app">
    <div id="banner">
        <b>Vue</b> - TEST Document Object Model (CRUD)
    </div>
    <div id="option">
        <div id="description">
            Zarządzanie obiektami:
        </div>
        <input type="text" id="howMany" name="howMany" placeholder="Wpisz ilość" /><br />
        <button class="Btn" @click="create()"> Stwórz </button>
        <button class="Btn" @click="add()"> Dodaj </button>
        <button class="Btn" @click="ddelete()"> Usuń </button>
        <button class="Btn" @click="update()"> Zaktualizuj </button>
        <button class="Btn" @click="clean()"> Wyczyść </button>
    </div>
    <div id="lista">
      <div v-for="object in selectors" :key="object.id">{{object}} obiekt</div>
    </div>
    <div id="czas">Czas wykonania w milisekundach: <span id="timer"></span> </div>
    <img alt="UAM" src="../assets/logo-uam.jpg">
  </div>
</template>

<script>
export default{
  name: 'app',
  data () {
    return {
      number: 0,
      selectors: [],
      operationStartTime: null,
      operationEndTime: null
    }
  },
  methods: {
    create () {
      this.operationStartTime = performance.now()
      let howMany = parseInt(document.getElementById('howMany').value)
      this.number = howMany
      let temp = []
      for (let i = 0; i < howMany; i++) {
        temp.push(
          i)
      }
      this.selectors = temp
      console.log(this.operationStartTime)
    },
    add () {
      this.operationStartTime = performance.now()
      let howMany = parseInt(document.getElementById('howMany').value)
      let oldNumber = this.number
      let newNumber = oldNumber + howMany
      let temp = this.selectors
      for (oldNumber; oldNumber < newNumber; oldNumber++) {
        temp.push(
          (oldNumber))
      }
      this.selectors = temp
      this.number = newNumber
      console.log(this.selectors)
      console.log(this.number)
    },
    ddelete () {
      this.operationStartTime = performance.now()
      let howMany = parseInt(document.getElementById('howMany').value)
      let oldNumber = this.number
      let newNumber = oldNumber - howMany
      let temp = this.selectors
      temp.splice(newNumber, howMany)
      this.selectors = temp
      this.number = newNumber
    },
    update () {
      this.operationStartTime = performance.now()
      let howMany = parseInt(document.getElementById('howMany').value)
      let min = Math.ceil(1)
      let max = Math.floor(1001)

      let oldNumber = this.number
      let newNumber = oldNumber - howMany
      for (newNumber - 1; newNumber < oldNumber; newNumber++) {
        let random = Math.floor(Math.random() * (max - min)) + min
        this.$set(this.selectors, newNumber, random)
      }
      this.number = oldNumber
      console.log(this.selectors)
    },
    clean () {
      this.operationStartTime = performance.now()
      this.selectors = []
      this.number = 0
    }
  },
  updated: function () {
    this.operationEndTime = performance.now()
    let temp = this.operationEndTime - this.operationStartTime
    document.getElementById('timer').innerHTML = temp
  }
}
</script>

// angular-aplikacja/src/app/TestUAM/testUAM.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-TestUAM',
  templateUrl: './testUAM.component.html',
  styleUrls: ['../app.component.css']
})
export class TestUAM {
  title = 'angular-aplikacja';
  selectors = [] as number[]
  number = 0
  operationStartTime = 0
  operationEndTime = 0
  temp = ''
  create() {
    this.operationStartTime = performance.now()
    let howMany = parseInt((<HTMLInputElement>document.getElementById("howMany")).value)
    this.number = howMany
    let temp = []
    for (let i = 0; i < howMany; i++) {
      temp.push(
        i)
    }
    this.selectors = temp
  }

  add() {
    this.operationStartTime = performance.now()
    let howMany = parseInt((<HTMLInputElement>document.getElementById("howMany")).value)
    let oldNumber = this.number
    let newNumber = oldNumber + howMany
    let temp = this.selectors
    for (oldNumber; oldNumber < newNumber; oldNumber++) {
      temp.push(
        (oldNumber))
    }
    this.selectors = temp
    this.number = newNumber
  }

  ddelete() {
    this.operationStartTime = performance.now()
    let howMany = parseInt((<HTMLInputElement>document.getElementById("howMany")).value)
    let oldNumber = this.number
    let newNumber = oldNumber - howMany
    let temp = this.selectors
    temp.splice(newNumber, howMany)
    this.selectors = temp
    this.number = newNumber
  }

  update() {
    this.operationStartTime = performance.now()
    let howMany = parseInt((<HTMLInputElement>document.getElementById("howMany")).value)
    let min = Math.ceil(1)
    let max = Math.floor(1001)

    let oldNumber = this.number
    let newNumber = oldNumber - howMany
    let temp = this.selectors;
    for (newNumber - 1; newNumber < oldNumber; newNumber++) {
      let random = Math.floor(Math.random() * (max - min)) + min
      temp[newNumber] = random;
    }
    this.number = oldNumber
  }

  clean() {
    this.operationStartTime = performance.now()
    this.selectors = []
    this.number = 0
  }

  ngAfterViewChecked() {
    this.operationEndTime = performance.now()
    this.temp = String(this.operationEndTime - this.operationStartTime);
    (<HTMLInputElement>document.getElementById('timer')).innerHTML = this.temp
  }
}
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<style>
  html,
  body {
    padding: 0;
    margin: 0;
  }

  b {
    font-size: 40px;
  }

  #banner {
    text-align: center;
    font-size: 30px;
    background-color: #c2c2c2;
    border-radius: 8px;
    border-style: solid;
    border-color: black;
    color: black;
  }

  #option {
    background-color: #c2c2c2;
    /* border: none; */
    color: black;
    text-align: center;
    text-decoration: none;
    display: block;
    font-size: 20px;
    border-color: black;
    width: 140px;
    position: fixed;
    left: 0;
    top: 0;
    border-style: solid;
    border-color: black;
  }

  button {
    background-color: #000000;
    /* border: none; */
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: block;
    font-size: 16px;
    border-radius: 8px;
    border-style: solid;
    border-color: #629749;
    width: 140px;
  }

  button:hover {
    background-color: #1e911e;
  }

  img {
    position: fixed;
    right: 0;
    top: 90%;
    width: 7%;
    margin-top: -2.5em;
  }

  #czas {
    position: fixed;
    left: 0;
    bottom: 0;
  }

  input[type=text] {
    font-size: 16px;
    border-radius: 8px;
    border-style: solid;
    border-color: #629749;
    width: 130px;
  }

  #lista {
    text-align: center;
    font-size: 25px;
  }

</style>

<!-- Toolbar -->
<div id=banner>
  <b>Angular</b> - TEST Document Object Model (CRUD)
</div>

<div class="content" role="main">
  <div id="option">
    <div id="description">
      Zarządzanie obiektami:
    </div>
    <input type="text" id="howMany" name="howMany" placeholder="Wpisz ilość" /><br />
    <button (click)="create()">Stwórz</button>
    <button (click)="add()">Dodaj</button>
    <button (click)="ddelete()">Usuń</button>
    <button (click)="update()">Zaktualizuj</button>
    <button (click)="clean()">Wyczyść</button>
  </div>
  <div id="lista">
    <div *ngFor="let selector of selectors; index as i; first as isFirst">{{selector + 1}} obiekt</div>
  </div>
</div>
<div id="czas">Czas wykonania w milisekundach: <span id="timer"></span> </div>
<div id=logo>
  <img alt="UAM" src="../assets/logo-uam.jpg">
</div>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
